# Generated by Django 5.2.7 on 2026-01-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_rename_displayname_track_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='allow_followers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='track',
            name='enable_chat',
            field=models.BooleanField(default=False),
        ),
    ]
