# Generated by Django 5.2.7 on 2026-01-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postlike_unique_post_like'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postlike',
            unique_together=set(),
        ),
    ]
