# Generated by Django 5.2.7 on 2026-01-12 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='post',
            name='displayname',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
