# Generated by Django 5.2.7 on 2026-01-12 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0005_remove_post_avatar_remove_post_displayname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post_authors', to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='author_object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
