# Generated by Django 5.2.7 on 2025-12-31 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('channel_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('channel_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_channel_messages', to='contenttypes.contenttype')),
                ('speaker_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_speaker_messages', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['channel_content_type', 'channel_object_id'], name='chat_app_ch_channel_7aca3c_idx'), models.Index(fields=['speaker_content_type', 'speaker_object_id'], name='chat_app_ch_speaker_4e8b60_idx'), models.Index(fields=['created_at'], name='chat_app_ch_created_a514d1_idx')],
            },
        ),
    ]
