# Generated by Django 5.2.7 on 2026-01-30 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chatmessage',
            name='chat_app_ch_speaker_4e8b60_idx',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='speaker_content_type',
        ),
        migrations.RemoveField(
            model_name='chatmessage',
            name='speaker_object_id',
        ),
    ]
