# Generated by Django 5.2.7 on 2026-01-27 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_rename_displayname_team_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.RemoveField(
            model_name='team',
            name='logo',
        ),
    ]
