# Generated by Django 5.2.7 on 2026-01-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_description_remove_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='allow_followers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='enable_chat',
            field=models.BooleanField(default=False),
        ),
    ]
