# Generated by Django 5.2.7 on 2025-12-31 16:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
        ('stopwatch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StopwatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elapsed_time', models.FloatField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopwatch_runs', to='races.race')),
                ('racedriver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopwatch_runs', to='races.racedriver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='RaceStopwatchRun',
        ),
    ]
