# Generated by Django 6.0.2 on 2026-02-21 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0001_initial'),
        ('clubs', '0002_initial'),
        ('drivers', '0001_initial'),
        ('events', '0001_initial'),
        ('locations', '0002_initial'),
        ('stores', '0001_initial'),
        ('teams', '0001_initial'),
        ('tracks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('allow_followers', models.BooleanField(default=True)),
                ('enable_chat', models.BooleanField(default=False)),
                ('race_type', models.CharField(choices=[('Lap Race', 'Lap Race'), ('Drag Race', 'Drag Race'), ('Crawler Comp', 'Crawler Comp'), ('Stopwatch Race', 'Stopwatch Race'), ('Long Jump', 'Long Jump'), ('Top Speed', 'Top Speed'), ('Judged Event', 'Judged Event')], default='Lap Race', max_length=30)),
                ('entry_type', models.CharField(blank=True, choices=[('Open', 'Open'), ('Invitational', 'Invitational')], default='Open', max_length=20, null=True)),
                ('transponder', models.CharField(blank=True, choices=[('LapMonitor', 'LapMonitor'), ('MyLaps', 'MyLaps')], max_length=10, null=True)),
                ('entry_locked', models.BooleanField(default=False)),
                ('race_finished', models.BooleanField(default=False)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='clubs.club')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='events.event')),
                ('judge_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_races', to='teams.team')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='locations.location')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='stores.store')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='teams.team')),
                ('track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='tracks.track')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RaceDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transponder', models.CharField(blank=True, choices=[('LapMonitor', 'LapMonitor'), ('MyLaps', 'MyLaps')], max_length=10, null=True)),
                ('finish_position', models.PositiveIntegerField(blank=True, null=True)),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_entries', to='builds.build')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_entries', to='drivers.driver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_drivers', to='races.race')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='race_drivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('race', 'driver', 'build'), name='unique_race_driver_build')],
            },
        ),
    ]
