# Generated by Django 5.2.7 on 2026-01-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racedriver',
            name='displayname',
        ),
        migrations.RemoveField(
            model_name='racedriver',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='racedriver',
            name='owner',
        ),
    ]
