# Generated by Django 6.0.2 on 2026-02-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_alter_race_race_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_type',
            field=models.CharField(choices=[('Lap Race', 'Lap Race'), ('Drag Race', 'Drag Race'), ('Crawler Comp', 'Crawler Comp'), ('Stopwatch Race', 'Stopwatch Race'), ('Long Jump', 'Long Jump'), ('Top Speed', 'Top Speed'), ('Judged Event', 'Judged Event'), ('Round Robin', 'Round Robin'), ('Swiss System', 'Swiss System')], default='Lap Race', max_length=30),
        ),
    ]
