# Generated by Django 5.2.7 on 2026-01-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_remove_racedriver_displayname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
