# Generated by Django 6.0.2 on 2026-04-22 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0005_alter_race_race_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='racedriver',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
