# Generated by Django 5.2.7 on 2026-01-30 07:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_build_allow_followers_build_enable_chat'),
        ('drivers', '0004_driver_allow_followers_driver_enable_chat'),
        ('races', '0005_race_allow_followers_race_enable_chat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='racedriver',
            name='unique_race_model',
        ),
        migrations.RemoveField(
            model_name='racedriver',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='racedriver',
            name='model_name',
        ),
        migrations.AddField(
            model_name='racedriver',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_entries', to='builds.build'),
        ),
        migrations.AddField(
            model_name='racedriver',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_entries', to='drivers.driver'),
        ),
        migrations.AlterField(
            model_name='racedriver',
            name='transponder',
            field=models.CharField(blank=True, choices=[('LapMonitor', 'LapMonitor'), ('MyLaps', 'MyLaps')], max_length=10, null=True),
        ),
        migrations.AddConstraint(
            model_name='racedriver',
            constraint=models.UniqueConstraint(fields=('race', 'build'), name='unique_race_build'),
        ),
    ]
