# Generated by Django 6.0.2 on 2026-04-30 07:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_devicepayload_options_remove_device_uuid_and_more'),
        ('races', '0006_alter_race_uuid_alter_racedriver_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='device',
            field=models.ForeignKey(blank=True, help_text='Single device used for the whole race (e.g. radar gun for Top Speed)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='races', to='devices.device'),
        ),
        migrations.CreateModel(
            name='RaceJudgeDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_assignments', to='devices.device')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_devices', to=settings.AUTH_USER_MODEL)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judge_devices', to='races.race')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('race', 'judge'), name='unique_device_per_judge_per_race')],
            },
        ),
    ]
