# Generated by Django 5.2.7 on 2026-01-30 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_build_allow_followers_build_enable_chat'),
        ('drivers', '0004_driver_allow_followers_driver_enable_chat'),
        ('races', '0006_remove_racedriver_unique_race_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='racedriver',
            name='unique_race_build',
        ),
        migrations.AddConstraint(
            model_name='racedriver',
            constraint=models.UniqueConstraint(fields=('race', 'driver', 'build'), name='unique_race_driver_build'),
        ),
    ]
