# Generated by Django 5.2.7 on 2026-02-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_remove_racedriver_unique_race_build_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='racedriver',
            name='finish_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
