# Generated by Django 6.0.1 on 2026-02-07 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_racedriver_finish_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Invitational', 'Invitational'), ('Qualifier', 'Qualifier')], default='Open', max_length=20, null=True),
        ),
    ]
