# Generated by Django 6.0.2 on 2026-07-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_race_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='transponder',
            field=models.CharField(blank=True, choices=[('LapMonitor', 'LapMonitor'), ('MyLaps', 'MyLaps'), ('Easylap', 'Easylap'), ('Trackmate', 'Trackmate')], max_length=10, null=True),
        ),
    ]
