# Generated by Django 6.0.2 on 2026-08-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0009_alter_race_transponder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='race_type',
            field=models.CharField(choices=[('Lap Race', 'Lap Race'), ('Crawler Comp', 'Crawler Comp'), ('Stopwatch Race', 'Stopwatch Race'), ('Long Jump', 'Long Jump'), ('Top Speed', 'Top Speed'), ('Rally', 'Rally'), ('Judged Event', 'Judged Event'), ('Drag Race', 'Drag Single Elimination'), ('Round Robin', 'Drag Round Robin'), ('Swiss System', 'Drag Swiss System')], default='Lap Race', max_length=30),
        ),
    ]
