# Generated by Django 6.0.1 on 2026-02-07 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0009_race_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='entry_type',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Invitational', 'Invitational')], default='Open', max_length=20, null=True),
        ),
    ]
