# Generated by Django 6.0.1 on 2026-02-20 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_alter_race_entry_type'),
        ('teams', '0006_team_allow_followers_team_enable_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='judge_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='judge_races', to='teams.team'),
        ),
    ]
