# Generated by Django 6.0.2 on 2026-09-03 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_alter_race_race_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='club',
        ),
        migrations.RemoveField(
            model_name='race',
            name='store',
        ),
        migrations.RemoveField(
            model_name='race',
            name='team',
        ),
    ]
