# Generated by Django 6.0.2 on 2026-02-21 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('locations', '0002_initial'),
        ('races', '0001_initial'),
        ('stores', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlocation',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_locations', to='locations.location'),
        ),
        migrations.AddField(
            model_name='eventrace',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_races', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventrace',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_races', to='races.race'),
        ),
        migrations.AddField(
            model_name='eventstore',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_stores', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventstore',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_stores', to='stores.store'),
        ),
        migrations.AddField(
            model_name='eventteam',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_teams', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_teams', to='teams.team'),
        ),
        migrations.AddConstraint(
            model_name='eventclub',
            constraint=models.UniqueConstraint(fields=('event', 'club'), name='unique_event_club'),
        ),
        migrations.AddConstraint(
            model_name='eventlocation',
            constraint=models.UniqueConstraint(fields=('event', 'location'), name='unique_event_location'),
        ),
        migrations.AddConstraint(
            model_name='eventrace',
            constraint=models.UniqueConstraint(fields=('event', 'race'), name='unique_event_race'),
        ),
        migrations.AddConstraint(
            model_name='eventstore',
            constraint=models.UniqueConstraint(fields=('event', 'store'), name='unique_event_store'),
        ),
        migrations.AddConstraint(
            model_name='eventteam',
            constraint=models.UniqueConstraint(fields=('event', 'team'), name='unique_event_team'),
        ),
    ]
