# Generated by Django 5.2.7 on 2025-12-31 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventInterest',
        ),
    ]
