# Generated by Django 5.2.7 on 2026-01-07 07:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_delete_eventinterest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_days',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
