# Generated by Django 5.2.7 on 2026-01-12 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_event_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
