# Generated by Django 6.0.2 on 2026-07-19 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_uuid_alter_teammember_uuid'),
        ('events', '0004_eventcheckin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='staff_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffed_events', to='teams.team'),
        ),
    ]
