# Generated by Django 5.2.7 on 2026-02-01 23:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_allow_followers_club_enable_chat'),
        ('events', '0006_event_allow_followers_event_enable_chat'),
        ('races', '0008_racedriver_finish_position'),
        ('stores', '0005_store_allow_followers_store_enable_chat'),
        ('teams', '0006_team_allow_followers_team_enable_chat'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_clubs', to='clubs.club')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_clubs', to='events.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_races', to='events.event')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_races', to='races.race')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_stores', to='events.event')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_stores', to='stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EventTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_teams', to='events.event')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_teams', to='teams.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
