# Generated by Django 5.2.7 on 2026-02-02 00:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventclub_eventrace_eventstore_eventteam'),
        ('locations', '0005_location_address1_location_address2_location_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_locations', to='events.event')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_locations', to='locations.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
