# Generated by Django 5.2.7 on 2026-02-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_club_allow_followers_club_enable_chat'),
        ('events', '0008_remove_event_location_eventlocation'),
        ('locations', '0005_location_address1_location_address2_location_city_and_more'),
        ('races', '0008_racedriver_finish_position'),
        ('stores', '0005_store_allow_followers_store_enable_chat'),
        ('teams', '0006_team_allow_followers_team_enable_chat'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='eventclub',
            constraint=models.UniqueConstraint(fields=('event', 'club'), name='unique_event_club'),
        ),
        migrations.AddConstraint(
            model_name='eventlocation',
            constraint=models.UniqueConstraint(fields=('event', 'location'), name='unique_event_location'),
        ),
        migrations.AddConstraint(
            model_name='eventrace',
            constraint=models.UniqueConstraint(fields=('event', 'race'), name='unique_event_race'),
        ),
        migrations.AddConstraint(
            model_name='eventstore',
            constraint=models.UniqueConstraint(fields=('event', 'store'), name='unique_event_store'),
        ),
        migrations.AddConstraint(
            model_name='eventteam',
            constraint=models.UniqueConstraint(fields=('event', 'team'), name='unique_event_team'),
        ),
    ]
