# Generated by Django 6.0.2 on 2026-02-21 19:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('allow_followers', models.BooleanField(default=True)),
                ('enable_chat', models.BooleanField(default=False)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('make', models.CharField(blank=True, max_length=255, null=True)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('bearings', models.CharField(blank=True, help_text='Enter bearings', max_length=255, null=True)),
                ('body', models.CharField(blank=True, help_text='Enter body', max_length=255, null=True)),
                ('bumper_front', models.CharField(blank=True, help_text='Enter bumper_front', max_length=255, null=True)),
                ('bumper_rear', models.CharField(blank=True, help_text='Enter bumper_rear', max_length=255, null=True)),
                ('camber_links', models.CharField(blank=True, help_text='Enter camber_links', max_length=255, null=True)),
                ('caster_blocks', models.CharField(blank=True, help_text='Enter caster_blocks', max_length=255, null=True)),
                ('chassis', models.CharField(blank=True, help_text='Enter chassis', max_length=255, null=True)),
                ('control_arms', models.CharField(blank=True, help_text='Enter control_arms', max_length=255, null=True)),
                ('cooling', models.CharField(blank=True, help_text='Enter cooling', max_length=255, null=True)),
                ('driveshafts', models.CharField(blank=True, help_text='Enter driveshafts', max_length=255, null=True)),
                ('esc', models.CharField(blank=True, help_text='Enter esc', max_length=255, null=True)),
                ('esc_motor', models.CharField(blank=True, help_text='Enter esc_motor', max_length=255, null=True)),
                ('fuel', models.CharField(blank=True, help_text='Enter fuel', max_length=255, null=True)),
                ('lights', models.CharField(blank=True, help_text='Enter lights', max_length=255, null=True)),
                ('motor', models.CharField(blank=True, help_text='Enter motor', max_length=255, null=True)),
                ('radio_system', models.CharField(blank=True, help_text='Enter radio_system', max_length=255, null=True)),
                ('rear_steer', models.CharField(blank=True, help_text='Enter rear_steer', max_length=255, null=True)),
                ('rims', models.CharField(blank=True, help_text='Enter rims', max_length=255, null=True)),
                ('scale', models.CharField(blank=True, help_text='Enter scale', max_length=255, null=True)),
                ('sensor', models.CharField(blank=True, help_text='Enter sensor', max_length=255, null=True)),
                ('servo', models.CharField(blank=True, help_text='Enter servo', max_length=255, null=True)),
                ('shocks', models.CharField(blank=True, help_text='Enter shocks', max_length=255, null=True)),
                ('shocks_front', models.CharField(blank=True, help_text='Enter shocks_front', max_length=255, null=True)),
                ('shocks_rear', models.CharField(blank=True, help_text='Enter shocks_rear', max_length=255, null=True)),
                ('transmission', models.CharField(blank=True, help_text='Enter transmission', max_length=255, null=True)),
                ('wheel_hubs', models.CharField(blank=True, help_text='Enter wheel_hubs', max_length=255, null=True)),
                ('wheels', models.CharField(blank=True, help_text='Enter wheels', max_length=255, null=True)),
                ('wheels_front', models.CharField(blank=True, help_text='Enter wheels_front', max_length=255, null=True)),
                ('wheels_rear', models.CharField(blank=True, help_text='Enter wheels_rear', max_length=255, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
    ]
