# Generated by Django 5.2.7 on 2026-01-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='bearings',
            field=models.CharField(blank=True, help_text='Enter bearings', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='body',
            field=models.CharField(blank=True, help_text='Enter body', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='bumper_front',
            field=models.CharField(blank=True, help_text='Enter bumper_front', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='bumper_rear',
            field=models.CharField(blank=True, help_text='Enter bumper_rear', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='camber_links',
            field=models.CharField(blank=True, help_text='Enter camber_links', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='caster_blocks',
            field=models.CharField(blank=True, help_text='Enter caster_blocks', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='chassis',
            field=models.CharField(blank=True, help_text='Enter chassis', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='control_arms',
            field=models.CharField(blank=True, help_text='Enter control_arms', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='cooling',
            field=models.CharField(blank=True, help_text='Enter cooling', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='driveshafts',
            field=models.CharField(blank=True, help_text='Enter driveshafts', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='esc',
            field=models.CharField(blank=True, help_text='Enter esc', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='esc_motor',
            field=models.CharField(blank=True, help_text='Enter esc_motor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='fuel',
            field=models.CharField(blank=True, help_text='Enter fuel', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='lights',
            field=models.CharField(blank=True, help_text='Enter lights', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='motor',
            field=models.CharField(blank=True, help_text='Enter motor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='radio_system',
            field=models.CharField(blank=True, help_text='Enter radio_system', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='rear_steer',
            field=models.CharField(blank=True, help_text='Enter rear_steer', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='rims',
            field=models.CharField(blank=True, help_text='Enter rims', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='scale',
            field=models.CharField(blank=True, help_text='Enter scale', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='sensor',
            field=models.CharField(blank=True, help_text='Enter sensor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='servo',
            field=models.CharField(blank=True, help_text='Enter servo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='shocks',
            field=models.CharField(blank=True, help_text='Enter shocks', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='shocks_front',
            field=models.CharField(blank=True, help_text='Enter shocks_front', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='shocks_rear',
            field=models.CharField(blank=True, help_text='Enter shocks_rear', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='transmission',
            field=models.CharField(blank=True, help_text='Enter transmission', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='wheel_hubs',
            field=models.CharField(blank=True, help_text='Enter wheel_hubs', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='wheels',
            field=models.CharField(blank=True, help_text='Enter wheels', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='wheels_front',
            field=models.CharField(blank=True, help_text='Enter wheels_front', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='build',
            name='wheels_rear',
            field=models.CharField(blank=True, help_text='Enter wheels_rear', max_length=255, null=True),
        ),
    ]
