# Generated by Django 6.0.2 on 2026-03-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='drive_type',
            field=models.CharField(blank=True, help_text='Enter drive_type', max_length=255, null=True),
        ),
    ]
