# Generated by Django 5.2.7 on 2026-01-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0003_build_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['display_name']},
        ),
        migrations.RenameField(
            model_name='build',
            old_name='displayname',
            new_name='display_name',
        ),
    ]
