# Generated by Django 5.2.7 on 2026-01-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0004_alter_build_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='allow_followers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='build',
            name='enable_chat',
            field=models.BooleanField(default=False),
        ),
    ]
