# Generated by Django 6.0.2 on 2026-04-30 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicepayload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devicepayload',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='device',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='devicepayload',
            name='payload_data',
        ),
        migrations.AddField(
            model_name='device',
            name='mac',
            field=models.CharField(default='n/a', max_length=17, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicepayload',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='devicepayload',
            name='name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='devicepayload',
            name='processed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='devicepayload',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicepayload',
            name='racedriver_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicepayload',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='devicepayload',
            name='value',
            field=models.CharField(default='n/a', max_length=32),
            preserve_default=False,
        ),
    ]
