# Generated by Django 6.0.2 on 2026-04-30 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_alter_devicepayload_options_remove_device_uuid_and_more'),
        ('teams', '0002_alter_team_uuid_alter_teammember_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='owner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='teams.team'),
        ),
        migrations.AddField(
            model_name='device',
            name='owner_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
