# Generated by Django 6.0.2 on 2026-05-07 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('devices', '0004_device_owner_team_device_owner_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='owner_team',
        ),
        migrations.RemoveField(
            model_name='device',
            name='owner_user',
        ),
        migrations.AddField(
            model_name='device',
            name='claimed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_devices', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='device',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['content_type', 'object_id'], name='devices_dev_content_7dc50f_idx'),
        ),
    ]
