# Generated by Django 6.0.2 on 2026-05-08 23:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_device_owner_team_remove_device_owner_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
