# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=17, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Device whitelist entry',
                'verbose_name_plural': 'Device whitelist',
                'ordering': ['mac'],
            },
        ),
    ]
