# Generated by Django 6.0.2 on 2026-02-21 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('destination_url', models.URLField()),
                ('active', models.BooleanField(default=True)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('owner_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('owner_content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
