# Generated by Django 6.0.1 on 2026-02-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urls_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClickEvent',
        ),
    ]
