# Generated by Django 6.0.1 on 2026-02-04 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('urls_app', '0002_delete_clickevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='owner_content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='owner_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
