# Generated by Django 6.0.1 on 2026-02-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls_app', '0003_shorturl_owner_content_type_shorturl_owner_object_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
