# Generated by Django 6.0.2 on 2026-04-22 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_verified_user_phone_number_user_sms_opt_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
