# Generated by Django 6.0.2 on 2026-09-11 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_follow_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verifier_uuid', models.UUIDField(editable=False)),
                ('verifier_email', models.EmailField(editable=False, max_length=254)),
                ('verifier_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('verified_uuid', models.UUIDField(editable=False)),
                ('verified_email', models.EmailField(editable=False, max_length=254)),
                ('verified_name', models.CharField(blank=True, editable=False, max_length=255)),
                ('verified_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_received', to=settings.AUTH_USER_MODEL)),
                ('verifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
