# Generated by Django 6.0.1 on 2026-02-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sms_opt_in',
            field=models.BooleanField(default=False),
        ),
    ]
