# Generated by Django 5.2.7 on 2025-12-31 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elapsed_time', models.FloatField(blank=True, null=True)),
                ('penalty_points', models.IntegerField(default=0)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_runs', to='races.race')),
                ('racedriver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_runs', to='races.racedriver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CrawlerRunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('milliseconds', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=255)),
                ('delta', models.IntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='crawler.CrawlerRun')),
            ],
            options={
                'ordering': ['milliseconds'],
            },
        ),
    ]
