# Generated by Django 5.2.7 on 2026-02-01 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builds', '0005_build_allow_followers_build_enable_chat'),
        ('crawler', '0001_initial'),
        ('drivers', '0004_driver_allow_followers_driver_enable_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerrunlog',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_logs', to='builds.build'),
        ),
        migrations.AddField(
            model_name='crawlerrunlog',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_logs', to='drivers.driver'),
        ),
    ]
