# Generated by Django 6.0.2 on 2026-02-21 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0001_initial'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlerrun',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_runs', to='races.race'),
        ),
        migrations.AddField(
            model_name='crawlerrun',
            name='racedriver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawler_runs', to='races.racedriver'),
        ),
        migrations.AddField(
            model_name='crawlerrunlog',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='crawler.crawlerrun'),
        ),
    ]
