# Generated by Django 5.2.7 on 2026-02-01 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_crawlerrunlog_build_crawlerrunlog_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlerrunlog',
            name='build',
        ),
        migrations.RemoveField(
            model_name='crawlerrunlog',
            name='driver',
        ),
    ]
