# Generated by Django 5.2.7 on 2025-12-31 21:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LapMonitorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField()),
                ('session_name', models.CharField(max_length=100)),
                ('session_date', models.DateTimeField()),
                ('session_kind', models.CharField(max_length=50)),
                ('session_duration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('driver_id', models.UUIDField()),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_transponder_id', models.CharField(max_length=50)),
                ('driver_rank', models.IntegerField()),
                ('lap_index', models.IntegerField()),
                ('lap_end_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lap_duration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lap_kind', models.CharField(max_length=50)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lapmonitor_results', to='races.race')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lapmonitor_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LapMonitor Result',
                'verbose_name_plural': 'LapMonitor Results',
                'indexes': [models.Index(fields=['session_id'], name='laprace_lap_session_18a42f_idx'), models.Index(fields=['driver_id'], name='laprace_lap_driver__4d25f8_idx'), models.Index(fields=['race', 'session_id', 'driver_id', 'lap_index'], name='laprace_lap_race_id_01ad40_idx')],
            },
        ),
    ]
