# Generated by Django 6.0.2 on 2026-02-21 19:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LapMonitorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_id', models.UUIDField()),
                ('session_name', models.CharField(max_length=100)),
                ('session_date', models.DateTimeField()),
                ('session_kind', models.CharField(max_length=50)),
                ('session_duration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('driver_id', models.UUIDField()),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_transponder_id', models.CharField(max_length=50)),
                ('driver_rank', models.IntegerField()),
                ('lap_index', models.IntegerField()),
                ('lap_end_time', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lap_duration', models.DecimalField(decimal_places=3, max_digits=10)),
                ('lap_kind', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'LapMonitor Result',
                'verbose_name_plural': 'LapMonitor Results',
            },
        ),
    ]
