# Generated by Django 6.0.2 on 2026-02-21 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laprace', '0001_initial'),
        ('races', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lapmonitorresult',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lapmonitor_results', to='races.race'),
        ),
        migrations.AddField(
            model_name='lapmonitorresult',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lapmonitor_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lapmonitorresult',
            index=models.Index(fields=['session_id'], name='laprace_lap_session_18a42f_idx'),
        ),
        migrations.AddIndex(
            model_name='lapmonitorresult',
            index=models.Index(fields=['driver_id'], name='laprace_lap_driver__4d25f8_idx'),
        ),
        migrations.AddIndex(
            model_name='lapmonitorresult',
            index=models.Index(fields=['race', 'session_id', 'driver_id', 'lap_index'], name='laprace_lap_race_id_01ad40_idx'),
        ),
    ]
