# Generated by Django 6.0.2 on 2026-02-21 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('judged', '0001_initial'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgedscore',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race'),
        ),
        migrations.AddField(
            model_name='judgedscore',
            name='racedriver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judged_scores', to='races.racedriver'),
        ),
        migrations.AddConstraint(
            model_name='judgedscore',
            constraint=models.UniqueConstraint(fields=('race', 'racedriver', 'judge'), name='unique_score_per_judge_driver'),
        ),
    ]
