# Generated by Django 6.0.1 on 2026-02-16 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judged', '0003_alter_judge_race_alter_judge_user'),
        ('races', '0010_alter_race_entry_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='judgedeventrunscore',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='races.race'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='judgedeventrunscore',
            name='racedriver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='races.racedriver'),
            preserve_default=False,
        ),
    ]
