# Generated by Django 6.0.1 on 2026-02-16 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judged', '0004_judgedeventrunscore_race_and_more'),
        ('races', '0010_alter_race_entry_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JudgedScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.FloatField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='judgedeventrun',
            name='unique_race_racedriver',
        ),
        migrations.RemoveConstraint(
            model_name='judgedeventrunscore',
            name='unique_judge_per_run_score',
        ),
        migrations.AddField(
            model_name='judgedscore',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='judgedscore',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.race'),
        ),
        migrations.AddField(
            model_name='judgedscore',
            name='racedriver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.racedriver'),
        ),
        migrations.RemoveField(
            model_name='judgedeventrun',
            name='race',
        ),
        migrations.RemoveField(
            model_name='judgedeventrun',
            name='racedriver',
        ),
        migrations.RemoveField(
            model_name='judgedeventrunscore',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='judgedeventrunscore',
            name='race',
        ),
        migrations.RemoveField(
            model_name='judgedeventrunscore',
            name='racedriver',
        ),
        migrations.RemoveField(
            model_name='judgedeventrunscore',
            name='run',
        ),
        migrations.AddConstraint(
            model_name='judgedscore',
            constraint=models.UniqueConstraint(fields=('race', 'racedriver', 'judge'), name='unique_score_per_judge_driver'),
        ),
        migrations.DeleteModel(
            name='JudgedEventRun',
        ),
        migrations.DeleteModel(
            name='JudgedEventRunScore',
        ),
    ]
