# Generated by Django 6.0.1 on 2026-02-16 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judged', '0005_judgedscore_and_more'),
        ('races', '0010_alter_race_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judgedscore',
            name='racedriver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judged_scores', to='races.racedriver'),
        ),
    ]
