# Generated by Django 6.0.1 on 2026-02-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('judged', '0007_alter_judge_user'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='judge',
            name='unique_judge_per_race',
        ),
        migrations.DeleteModel(
            name='Judge',
        ),
    ]
