# Generated by Django 5.2.7 on 2025-12-31 15:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('round_number', models.PositiveSmallIntegerField()),
                ('model1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_lane1_races', to='races.racedriver')),
                ('model2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drag_lane2_races', to='races.racedriver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_race_rounds', to='races.race')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drag_won_rounds', to='races.racedriver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
