# Generated by Django 5.2.7 on 2026-01-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragrace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragrace',
            name='round_number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
