# Generated by Django 6.0.2 on 2026-02-21 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dragrace', '0001_initial'),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragrace',
            name='model1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_lane1_races', to='races.racedriver'),
        ),
        migrations.AddField(
            model_name='dragrace',
            name='model2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drag_lane2_races', to='races.racedriver'),
        ),
        migrations.AddField(
            model_name='dragrace',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_race_rounds', to='races.race'),
        ),
        migrations.AddField(
            model_name='dragrace',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drag_won_rounds', to='races.racedriver'),
        ),
    ]
