# Generated by Django 6.0.2 on 2026-02-21 19:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopSpeedRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topspeed', models.IntegerField(blank=True, null=True)),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topspeed_runs', to='races.race')),
                ('racedriver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topspeed_runs', to='races.racedriver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
