# Generated by Django 6.0.2 on 2026-03-17 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topspeed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topspeedrun',
            name='topspeed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
