# Generated by Django 6.0.2 on 2026-04-22 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topspeed', '0002_alter_topspeedrun_topspeed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topspeedrun',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
