# Generated by Django 5.2.7 on 2026-01-09 00:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clublocation',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='clubmember',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='clublocation',
            constraint=models.UniqueConstraint(fields=('club', 'location'), name='unique_club_location'),
        ),
        migrations.AddConstraint(
            model_name='clubmember',
            constraint=models.UniqueConstraint(fields=('club', 'user'), name='unique_club_member'),
        ),
    ]
