# Generated by Django 5.2.7 on 2026-01-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='displayname',
            new_name='display_name',
        ),
    ]
