# Generated by Django 5.2.7 on 2026-01-27 04:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_rename_displayname_club_display_name'),
        ('teams', '0004_rename_displayname_team_display_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubteams', to='clubs.club')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubteams', to='teams.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
