# Generated by Django 5.2.7 on 2026-01-27 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_clubteam'),
        ('teams', '0004_rename_displayname_team_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubteam',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='clubs.club'),
        ),
        migrations.AlterField(
            model_name='clubteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='teams.team'),
        ),
    ]
