# Generated by Django 5.2.7 on 2026-01-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_alter_clubteam_club_alter_clubteam_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='allow_followers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='club',
            name='enable_chat',
            field=models.BooleanField(default=False),
        ),
    ]
