# Generated by Django 6.0.2 on 2026-09-24 03:56

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('stores', '0005_remove_store_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Percent off the cart subtotal, e.g. 25 for 25% off.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited uses.', null=True)),
                ('times_used', models.PositiveIntegerField(default=0, editable=False)),
                ('store', models.ForeignKey(blank=True, help_text='Leave blank to allow this code at every store.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_codes', to='stores.store')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='cart.promocode'),
        ),
        migrations.AddConstraint(
            model_name='promocode',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='cart_promocode_code_ci_unique'),
        ),
    ]
