from django.db import models
from rekjrc.base_models import BaseModel
from races.models import Race, RaceDriver


class SwissRace(BaseModel):
    """
    One head-to-head matchup inside a Swiss (Swiss-system) bracket.

    Structure mirrors DragRace exactly:
      - round_number  : which Swiss round this matchup belongs to (1, 2, 3 …)
      - race          : the parent Race
      - model1/model2 : the two competing RaceDrivers (model2 is None for a BYE)
      - winner        : set when the matchup is resolved

    Round 1 is seeded randomly by Start_.
    Subsequent rounds are generated by Swiss_ GET once every matchup in the
    current round has a winner — winners are paired with winners, losers with
    losers, within each score group (Swiss pairing).

    The tournament ends when all drivers have played ceil(log2(N)) rounds,
    OR when every score-group pairing would only produce rematches (the view
    detects this and sets ready_to_finish).
    """

    round_number = models.PositiveSmallIntegerField(default=1)
    race = models.ForeignKey(
        Race,
        on_delete=models.CASCADE,
        related_name='swiss_rounds',
    )
    model1 = models.ForeignKey(
        RaceDriver,
        on_delete=models.CASCADE,
        related_name='swiss_lane1_races',
    )
    model2 = models.ForeignKey(
        RaceDriver,
        on_delete=models.SET_NULL,
        related_name='swiss_lane2_races',
        null=True,
        blank=True,
    )
    winner = models.ForeignKey(
        RaceDriver,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='swiss_won_rounds',
    )

    class Meta:
        ordering = ['round_number', 'id']

    def __str__(self):
        return f"Round {self.round_number}: {self.model1} vs {self.model2 or 'BYE'}"
