# Generated by Django 5.2.7 on 2025-12-31 15:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongJumpRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feet', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('inches', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)])),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longjump_runs', to='races.race')),
                ('racedriver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='longjump_runs', to='races.racedriver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
