# Generated by Django 6.0.2 on 2026-02-22 00:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0002_alter_race_race_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundRobinRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_lane1_races', to='races.racedriver')),
                ('model2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rr_lane2_races', to='races.racedriver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_robin_matchups', to='races.race')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rr_won_matchups', to='races.racedriver')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
