# Generated by Django 6.0.2 on 2026-02-21 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationtrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_tracks', to='tracks.track'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='locations_l_latitud_739c67_idx'),
        ),
        migrations.AddConstraint(
            model_name='locationtrack',
            constraint=models.UniqueConstraint(fields=('location', 'track'), name='unique_location_track'),
        ),
    ]
