# Generated by Django 5.2.7 on 2026-01-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_location_allow_followers_location_enable_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='zip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
