# Generated by Django 5.2.7 on 2026-02-02 01:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location_address1_location_address2_location_city_and_more'),
        ('tracks', '0005_track_allow_followers_track_enable_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.CreateModel(
            name='LocationTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_tracks', to='locations.location')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_tracks', to='tracks.track')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('location', 'track'), name='unique_location_track')],
            },
        ),
    ]
