# Generated by Django 5.2.7 on 2026-01-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='store',
            name='logo',
        ),
    ]
