# Generated by Django 5.2.7 on 2026-01-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_remove_store_banner_image_remove_store_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='displayname',
            new_name='display_name',
        ),
    ]
