# Generated by Django 6.0.2 on 2026-08-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_storefront_enabled',
            field=models.BooleanField(default=False, help_text="Turn this on to let customers browse and buy this store's products online. Requires a connected Stripe account below before checkout will actually work."),
        ),
        migrations.AddField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='store',
            name='stripe_account_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='stripe_payouts_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
