# Generated by Django 6.0.2 on 2026-08-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_store_is_storefront_enabled_store_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='stripe_account_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='stripe_charges_enabled',
        ),
        migrations.RemoveField(
            model_name='store',
            name='stripe_details_submitted',
        ),
        migrations.RemoveField(
            model_name='store',
            name='stripe_payouts_enabled',
        ),
        migrations.AlterField(
            model_name='store',
            name='is_storefront_enabled',
            field=models.BooleanField(default=False, help_text="Turn this on to let customers browse and buy this store's products online. Requires this store's Stripe keys to already be set in .env (STRIPE_<id>_SECRET_KEY, etc. -- ask Jason) before checkout will actually work."),
        ),
    ]
