# Generated by Django 6.0.2 on 2026-09-24 03:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_promocode_cart_promo_code_and_more'),
        ('orders', '0002_remove_order_application_fee_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.promocode'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code_text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
