# Generated by Django 6.0.2 on 2026-04-07 18:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('races', '0005_alter_race_race_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DragDouble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bracket', models.CharField(choices=[('W', 'Winners'), ('L', 'Losers'), ('F', 'Final')], default='W', max_length=1)),
                ('round_number', models.PositiveSmallIntegerField(default=1)),
                ('model1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_double_lane1_races', to='races.racedriver')),
                ('model2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drag_double_lane2_races', to='races.racedriver')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drag_double_rounds', to='races.race')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drag_double_won_rounds', to='races.racedriver')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
