# Generated by Django 6.0.2 on 2026-04-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragdouble', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dragdouble',
            name='model1_record',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dragdouble',
            name='model2_record',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dragdouble',
            name='bracket',
            field=models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('F', 'Final')], default='W', max_length=1),
        ),
    ]
