# Generated by Django 6.0.2 on 2026-04-22 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragdouble', '0002_dragdouble_model1_record_dragdouble_model2_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragdouble',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
