# Generated by Django 6.0.2 on 2026-09-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='price_override',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in USD.', max_digits=8),
            preserve_default=False,
        ),
    ]
